apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-deployment-{{ .Values.org }}
  labels:
    app: peer-{{ .Values.org }}
    name: peer-{{ .Values.org }}
spec:
  selector:
    matchLabels:
      app: peer-{{ .Values.org }}
  replicas: 1 {{/* ${{REPLICAS}} */}}
  template:
    metadata:
      #          annotations:
      #            sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: peer-{{ .Values.org }}
    spec:
      volumes:
        - name: certs
          projected:
            sources:
              - secret:
                  name: certs-{{ .Values.org }}
                  items:
                  {{- include "certificates.decode" (merge (deepCopy .) .Values.peer) | nindent 12 }}

        - name: fabric-core-yaml
          configMap:
            name: fabric-core-yaml-cm

        - name: external-builders
          configMap:
            name: external-builers-cm
            defaultMode: 0777

      containers:
        - name: peer
          ports:
            - name: peer-port
              containerPort: 7051
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          volumeMounts:
            - name: certs
              mountPath: /etc/hyperledger/crypto-config #/ordererOrganizations/${DOMAIN}
            - name: fabric-core-yaml
              mountPath: /etc/hyperledger/fabric
            - name: external-builders
              mountPath: /external-builders/bin

          image: >-
            {{ tpl .Values.images.peer . }}
          {{/*            ${IMAGE_PATH}@sha256:${IMAGE_TAG}*/}}
          envFrom:
            - configMapRef:
                name: common-{{ .Values.org }}
            - configMapRef:
                name: peer-{{ .Values.org }}
          env:
            - name: CORE_PEER_POSTGRES_DATASOURCENAME
              value: user=$(DB_USERNAME) dbname=$(DB_NAME) password=$(DB_PASSWORD) host=$(DB_HOST) port=$(DB_PORT) sslmode=disable
          {{/*          command: ["ls", "-l", "/etc/hyperledger/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com"]*/}}


          #          resources:
          #            limits:
          #              cpu: ${CPULIMIT}
          #              memory: ${MEMORYLIMIT}
          #            requests:
          #              cpu: ${CPUREQUEST}
          #              memory: ${MEMORYREQUEST}
          #              readinessProbe:
          #                httpGet:
          #                  path: /health/check
          #                  port: 8080
          #                initialDelaySeconds: 10
          #              livenessProbe:
          #                httpGet:
          #                  path: /health/check
          #                  port: 8080
          #                initialDelaySeconds: 10
