kind: Service
apiVersion: v1
metadata:
  name: {{ tpl .Values.peerOrgName . }}
  namespace:  {{ .Values.NAMESPACE }}
spec:
  ports:
    - name: peerport
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: chaincodeserverport
      protocol: TCP
      port: 7052
      targetPort: 7052
  selector:
    app: peer-{{ .Values.org }}