apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-{{ .Values.org }}
data:
  DOMAIN: {{ .Values.domain }}
  processor.timeout: '1'
  cnft.wallet.address: 'http://egress-nginx.${NAMESPACE}.svc:8088/cnft-gate'
  dfa.integration.service.port: '9185'

  DFA_INTEGRATION_JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=95.0  -Dfile.encoding=UTF-8'

  ORDERER_GENERAL_LISTENADDRESS: '0.0.0.0'
  # ORDERER_GENERAL_LISTENPORT: '7050' # from common-cm
  ORDERER_GENERAL_GENESISMETHOD: 'file'
#  ORDERER_GENERAL_GENESISFILE: '/etc/hyperledger/channel-artifacts/genesis.block'
  ORDERER_GENERAL_BOOTSTRAPFILE: '/etc/hyperledger/channel-artifacts/genesis.block'

#      fabric.cfg.path: '$BASE_DIR/hlf/config'
#      orderer.consensus.snapdir: '$BASE_DIR/persistence/orderer/etcdraft/snapshot'
#      orderer.consensus.waldir: '$BASE_DIR/persistence/orderer/etcdraft/wal'