kind: Service
apiVersion: v1
metadata:
  name: dns-chaincode
spec:
  ports:
    - name: chaincodeport
      protocol: TCP
      port: {{ .Values.dnsChaincodePort }}
      targetPort: {{ .Values.dnsChaincodePort }}
  selector:
    app: dns-chaincode