kind: Endpoints
apiVersion: v1
metadata:
  name:   {{ default "peer0" .Values.peer.newOrgPeerName }}-{{ .Values.peer.newOrg }}
subsets:
  - addresses:
    - ip: {{ .Values.peer.newOrgIp }}
    ports:
      - name: peerport
        port: {{ .Values.peer.newPeerPort }}
        protocol: TCP
      - name: wwwport
        port: {{ default "80" .Values.peer.newWwwPort }}
        protocol: TCP
