apiVersion: v1
kind: Service
metadata:
  name: peer0
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.PEER0_PORT }}
      targetPort: {{ .Values.PEER0_PORT }}
      protocol: TCP
  clusterIP: None
  selector:
    app:  {{ .Chart.Name }}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-peer
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: peer0
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:


      volumes:
        - name: crypto-config
          emptyDir: {}
#          hostPath:
#            path: crypto-config
#            type: Directory
        - name: docker-socket
          hostPath:
            path:  /var/run/docker.sock
            type: Socket


      containers:

        - name: peer
          image: hyperledger/fabric-peer:1.4.8
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sh", "-c", "peer node start"]
          env:
            - name: CORE_PEER_ID
              value: {{ .Values.PEER_NAME }}.{{ .Values.ORG }}.{{ .Values.DOMAIN }}
            - name: CORE_PEER_LOCALMSPID
              value: {{ .Values.ORG }}
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CORE_PEER_ADDRESS
#              value: {{ .Values.PEER_NAME }}.{{ .Values.ORG }}.{{ .Values.DOMAIN }}:{{ .Values.PEER0_PORT }}
              value: {{ .Values.PEER_NAME }}.$(CLUSTER_NAMESPACE).{{ .Values.clusterDomain }}:{{ .Values.PEER0_PORT }}
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:{{ .Values.PEER0_PORT }}
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
              value: fabric-starter_default
            - name: CORE_VM_DOCKER_ATTACHSTDOUT
              value: "true"

            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: {{ .Values.PEER_NAME }}.{{ .Values.ORG }}.{{ .Values.DOMAIN }}:{{ .Values.PEER0_PORT }}

            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/crypto/peer/msp
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/crypto/peer/tls/server.key
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/crypto/peer/tls/server.crt
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/crypto/peer/tls/ca.crt
          volumeMounts:
            - name: crypto-config
              subPath: peerOrganizations/{{ .Values.ORG }}.{{ .Values.DOMAIN }}/peers/{{ .Values.PEER_NAME }}.{{ .Values.ORG }}.{{ .Values.DOMAIN }}
              mountPath: /etc/hyperledger/crypto/peer
            - name: docker-socket
              mountPath: /host/var/run/docker.sock

#            - peer:/var/hyperledger/production
#            - ${FABRIC_STARTER_HOME:-.}/crypto-config/hosts:/etc/hosts



