apiVersion: v1
kind: ConfigMap
metadata:
  name: common
data:
  ORG: {{ .Values.org }}
  DOMAIN: {{ .Values.domain }}

{{/*  MY_IP: {{ .Values.myIp | default "" }}*/}}
{{/*  BOOTSTRAP_IP: {{ .Values.bootstrapIp | default "" }}*/}}

  ORDERER_NAME: {{ .Values.ORDERER_NAME | default "orderer"  }}

  CORE_PEER_ID: {{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_PEER_CHAINCODEADDRESS:  {{ .Values.peerName }}.{{ .Values.NAMESPACE }}:7052
  CORE_PEER_ADDRESS:  {{ .Values.peerName }}.{{ .Values.NAMESPACE }}:7051


  CRYPTO_CONFIG_DIR: /etc/hyperledger/crypto-config
  CORE_PEER_LOCALMSPID: {{ .Values.org }}
  CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@${{ .Values.org }}.{{ .Values.domain }}/msp
  ENROLL_ID: admin
  ENROLL_SECRET: adminpw
  {{/*  BOOTSTRAP_EXTERNAL_PORT: */}}


  CORE_LEDGER_STATE_STATEDATABASE: 'PostgreSQL'
  DB_HOST: 'tkled-mvp000256.vm.esrt.cloud.sbrf.ru'
  DB_PORT: '5433'
  CORE_PEER_POSTGRES_SCHEMANAME: public
  DB_NAME: dfabch
  DB_USERNAME: dfa_tech_account

  CHANNEL_NAME: 'cnft'
  ORDERER_CA: /etc/hyperledger/crypto-config/peerOrganizations/${ORG}.${DOMAIN}/orderer/tlsca/tlsca.${DOMAIN}-cert.pem
  OSN_PORT: '7150'
  ORDERER_ADDRESS: orderer.${DOMAIN}:7150
  CHAINCODE_NAME: 'cnft'

  FABRIC_LOGGING_SPEC: INFO
  CORE_PEER_LISTENADDRESS: '0.0.0.0:7051'
  CORE_CHAINCODE_JAVA_RUNTIME: 'enterprisedlt/fabric-jar-env'
  GODEBUG: 'netdns'
#      fabric.cfg.path: '$BASE_DIR/hlf/config'

  EXTERNAL_CHAINCODE_ADDRESS: cnft-chaincode.{{ .Values.NAMESPACE }}:3737
