apiVersion: v1
kind: ConfigMap
metadata:
  name: common-{{ .Values.org }}
data:
  ORG: {{ .Values.org }}
  DOMAIN: {{ .Values.domain }}
  PEER_NAME: {{ .Values.peerName | default "peer0" }}
  PEER_ORG_NAME: {{ tpl .Values.peerOrgName . }}
  PEER0_PORT: "{{ .Values.peer0Port | default 7051 }}"

  ORDERER_NAME: {{ .Values.ORDERER_NAME | default "orderer"  }}
  ORDERER_DOMAIN: {{ .Values.domain }}

  FABRIC_VERSION: {{ .Values.FABRIC_VERSION }}
  {{/*  MY_IP: {{ .Values.myIp | default "" }}*/}}
  {{/*  BOOTSTRAP_IP: {{ .Values.bootstrapIp | default "" }}*/}}

  CORE_PEER_ADDRESS: "{{ tpl .Values.peerOrgName . }}.{{ .Values.NAMESPACE }}:{{ .Values.peerPort | default 7051 }}"

  CRYPTO_CONFIG_DIR: /etc/hyperledger/crypto-config
  CORE_PEER_LOCALMSPID: {{ .Values.org }}

  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/ca.crt
  CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp

  EXTERNAL_CHAINCODE_ADDRESS: cnft-chaincode.{{ .Values.NAMESPACE }}:3737



  ORDERER_GENERAL_LOCALMSPID: 'orderer.{{ .Values.domain }}'
  ORDERER_GENERAL_LOCALMSPDIR: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/msp
  ORDERER_GENERAL_LISTENPORT: '7050'
  ORDERER_BATCH_TIMEOUT: "5"

  ORDERER_GENERAL_TLS_ENABLED: 'true'
  ORDERER_GENERAL_TLS_PRIVATEKEY: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key
  ORDERER_GENERAL_TLS_CERTIFICATE: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
  ORDERER_GENERAL_TLS_ROOTCAS: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/ca.crt
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key




  ENROLL_ID: admin
  ENROLL_SECRET: {{ .Values.enroll_secret }}
  {{/*  BOOTSTRAP_EXTERNAL_PORT: */}}


  CORE_LEDGER_STATE_STATEDATABASE: 'PostgreSQL'
  DB_HOST: 'tkled-mvp000256.vm.esrt.cloud.sbrf.ru'
  DB_PORT: '5433'
  CORE_PEER_POSTGRES_SCHEMANAME: public
  DB_NAME: dfabch
  DB_USERNAME: dfa_tech_account

  CHANNEL_NAME: 'cnft'
  ORDERER_CA: /etc/hyperledger/crypto-config/peerOrganizations/${ORG}.${DOMAIN}/orderer/tlsca/tlsca.${DOMAIN}-cert.pem
  OSN_PORT: '7150'
# ORDERER_ADDRESS: orderer.${DOMAIN}:7150
  CHAINCODE_NAME: 'cnft'

  FABRIC_LOGGING_SPEC: {{ .Values.logLevel }}
  GODEBUG: 'netdns'
  #      fabric.cfg.path: '$BASE_DIR/hlf/config'

  CRYPTO_ALGORITHM: {{ "SW" | default .Values.cryptoAlgorithm }}

  TMP_DIR: {{ .Values.tmpDir }}