apiVersion: v1
kind: ConfigMap
metadata:
  name: common-{{ .Values.org }}
data:
  ORG: {{ .Values.org }}
  DOMAIN: {{ .Values.domain }}
  PEER_NAME: {{ .Values.peerName | default "peer0" }}
  PEER_ORG_NAME: {{ tpl .Values.peerOrgName . }}
  PEER0_PORT: "{{ .Values.peer0Port | default 7051 }}"

  ORDERER_NAME: {{ .Values.ordererName | default "orderer"  }}
  ORDERER_DOMAIN: {{ default .Values.domain .Values.ordererDomain }}

  FABRIC_VERSION: {{ .Values.FABRIC_VERSION }}
  {{/*  MY_IP: {{ .Values.myIp | default "" }}*/}}
  {{/*  BOOTSTRAP_IP: {{ .Values.bootstrapIp | default "" }}*/}}

  CORE_PEER_ADDRESS: "{{ tpl .Values.peerOrgName . }}.{{ .Values.domain }}:{{ .Values.peerPort | default 7051 }}"

  CRYPTO_CONFIG_DIR: /etc/hyperledger/crypto-config
  CORE_PEER_LOCALMSPID: {{ .Values.org }}

  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/ca.crt
  CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp



  ORDERER_GENERAL_LOCALMSPID: {{ include "orderer.nameDomain" .Values }}
  ORDERER_GENERAL_LOCALMSPDIR: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ include "orderer.nameDomain" .Values}}/msp
  ORDERER_GENERAL_LISTENPORT: "7050"
  ORDERER_BATCH_TIMEOUT: "5"

  ORDERER_GENERAL_TLS_ENABLED: 'true'
  ORDERER_GENERAL_TLS_PRIVATEKEY: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key
  ORDERER_GENERAL_TLS_CERTIFICATE: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
  ORDERER_GENERAL_TLS_ROOTCAS: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/ca.crt
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key


  ENROLL_ID: admin
  {{/*  BOOTSTRAP_EXTERNAL_PORT: */}}


  DB_HOST: {{ .Values.DB_HOST }}
  DB_PORT: "{{ .Values.DB_PORT }}"
  DB_NAME: {{ .Values.DB_NAME }}
  DB_USERNAME: {{ .Values.DB_USERNAME }}

  CORE_PEER_POSTGRES_SCHEMANAME: {{ .Values.CORE_PEER_POSTGRES_SCHEMANAME }}
  CORE_LEDGER_STATE_STATEDATABASE: {{ .Values.CORE_LEDGER_STATE_STATEDATABASE }}
  CORE_PEER_POSTGRES_TABLEPREFIX: {{ .Values.CORE_PEER_POSTGRES_TABLEPREFIX }}
  ORDERER_POSTGRES_TABLEPREFIX: {{ .Values.ORDERER_POSTGRES_TABLEPREFIX }}


  CRYPTO_ALGORITHM: {{ "SW" | default .Values.cryptoAlgorithm }}

  TMP_DIR: {{ .Values.tmpDir }}