NAMESPACE: &namespace default
logLevel: INFO # DEBUG

org: &org org1
peerName: peer0
domain: &domain default
#bootstrapIp: ''
#myIp: ""
authMode: ADMIN

peerOrgName: "{{ .Values.peerName }}-{{ .Values.org }}"

ordererName: orderer

FABRIC_VERSION: 2.3.3

enroll_secret: adminpw

genesisBlock: crypto-config/configtx/{{ .Values.domain }}/genesis.pb

tmpDir: /tmp

images:
  orderer: hyperledger/fabric-orderer:{{ .Values.FABRIC_VERSION }}
  peer: hyperledger/fabric-peer:{{ .Values.FABRIC_VERSION }}
  fabric_tools_extended: olegabu/fabric-tools-extended:2x
  fabric_starter_rest: olegabu/fabric-starter-rest:2x
  dns_chaincode: olegabu/dns-chaincode:2x
  fabric_sdk: olegabu/fabric-sdk-api:2x

peer0Port: 7051

common:
  env:
    - name: ORG
      value: *org
    - name: DOMAIN
      value: *domain


orderer:
  certificatePathes:
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/ca/ca.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/ca/priv_sk

    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.domain }}-cert.pem

    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/msp/keystore/priv_sk
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/msp/signcerts/{{ .Values.ordererName }}.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.domain }}-cert.pem

    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/tls/ca.crt
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/tls/server.crt
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.ordererName }}.{{ .Values.domain }}/tls/server.key

    - crypto-config/ordererOrganizations/{{ .Values.domain }}/tlsca/tlsca.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/tlsca/priv_sk

    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/keystore/priv_sk
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/signcerts/Admin@{{ .Values.domain }}-cert.pem
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.domain }}-cert.pem

peer:
  certificatePathes:
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/ca/ca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/ca/priv_sk

    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem

    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/keystore/priv_sk
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/signcerts/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem

    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/tls/ca.crt
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/tls/server.crt
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/tls/server.key

    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/tlsca/tlsca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/tlsca/priv_sk

    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts/Admin@{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts/ca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/keystore/priv_sk
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/signcerts/Admin@{{ .Values.org }}.{{ .Values.domain }}-cert.pem
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts/tlsca.{{ .Values.org }}.{{ .Values.domain }}-cert.pem
