NAMESPACE: &namespace default
logLevel: INFO # DEBUG

org: &org org1
peerName: peer0
domain: &domain default
ordererDomain: *domain
#bootstrapIp: ''
#myIp: ""

enroll_secret: adminpw

images:
  orderer: hyperledger/fabric-orderer:{{ .Values.FABRIC_VERSION }}
  peer: hyperledger/fabric-peer:{{ .Values.FABRIC_VERSION }}
  fabric_tools_extended: olegabu/fabric-tools-extended:2x
  fabric_starter_rest: olegabu/fabric-starter-rest:2x
  dns_chaincode: olegabu/dns-chaincode:2x
  fabric_sdk: olegabu/fabric-sdk-api:2x


CORE_LEDGER_STATE_STATEDATABASE: PostgreSQL
DB_HOST: test
DB_PORT: 5433
DB_NAME: test
DB_USERNAME: test
CORE_PEER_POSTGRES_SCHEMANAME: test
CORE_PEER_POSTGRES_TABLE_PREFIX: test
ORDERER_POSTGRES_TABLE_PREFIX: test
