NAMESPACE: &namespace default
logLevel: INFO # DEBUG

org: &org org1
peerName: peer0
domain: &domain default
#bootstrapIp: ''
#myIp: ""
authMode: ADMIN

peerOrgName: "{{ .Values.peerName }}-{{ .Values.org }}"

ordererName: orderer

FABRIC_VERSION: 2.3.3

enroll_secret: adminpw

genesisBlock: crypto-config/configtx/{{ .Values.domain }}/genesis.pb

tmpDir: /tmp

images:
  orderer: hyperledger/fabric-orderer:{{ .Values.FABRIC_VERSION }}
  peer: hyperledger/fabric-peer:{{ .Values.FABRIC_VERSION }}
  fabric_tools_extended: olegabu/fabric-tools-extended:2x
  fabric_starter_rest: olegabu/fabric-starter-rest:2x
  dns_chaincode: olegabu/dns-chaincode:2x
  fabric_sdk: olegabu/fabric-sdk-api:2x

peer0Port: 7051

CORE_LEDGER_STATE_STATEDATABASE: PostgreSQL
DB_HOST: test
DB_PORT: 5433
CORE_PEER_POSTGRES_SCHEMANAME: test
DB_NAME: test
DB_USERNAME: test
POSTGRES_TABLE_PREFIX: test
