apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
  labels:
    app: ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:


      volumes:
        - name: crypto-config
          emptyDir: {}
        #          hostPath:
        #            path: crypto-config
        #            type: Directory
        - name: certs
          projected:
            sources:
              - secret:
                  name: fabric-dfa-certs
                  items:
                    - key: sk.pem
                      path: peerOrganizations/org1.example.com/ca/sk.pem
                    - key: signcert
                      path: peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
      containers:
        #        - name: ca.${ORG:-org1}.${DOMAIN:-example.com}
        - name: ca
          #          image: ${DOCKER_REGISTRY:-docker.io}/hyperledger/fabric-ca:${FABRIC_VERSION:-1.4.8}
          image: registry.sigma.sbrf.ru/ci01146627/ci02605576_bchhub/fabric-peer-sber:latest
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server/ca
            - name: FABRIC_CA_SERVER_LDAP_USERFILTER
              value: (cn=%s)
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.ORG }}.{{ .Values.DOMAIN }}/ca/ca.{{ .Values.ORG }}.{{ .Values.DOMAIN }}-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.ORG }}.{{ .Values.DOMAIN }}/ca/sk.pem
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.ORG }}.{{ .Values.DOMAIN }}/tlsca/tlsca.{{ .Values.ORG }}.{{ .Values.DOMAIN }}-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.ORG }}.{{ .Values.DOMAIN }}/tlsca/sk.pem
            - name: ENROLL_ID
              value: admin
            - name: ENROLL_SECRET
              value: adminpw
          volumeMounts:
            #            - mountPath: /etc/hyperledger/crypto-config
            #              name: crypto-config
            - mountPath: /etc/hyperledger/fabric-ca-server/ca/fabric-ca-server-config-org1.yaml
              subPath: ca/fabric-ca-server-config-{{ .Values.ORG }}.yaml
              name: crypto-config
            - name: certs
              mountPath: /etc/hyperledger/crypto-config
          command: ["sh", "-c", "sleep 2; echo ; cat /etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/ca/* ; echo; fabric-ca-server start -b ${ENROLL_ID}:${ENROLL_SECRET} -d --ca.name=default"]
