apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include "orderer-generate.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "orderer-generate.labels" . }}
  template:
    metadata:
      labels:
        {{ include "orderer-generate.labels" . }}
    spec:
      initContainers:
        - name: orderer-pre-install
          image: {{ .Values.images.fabric_tools_extended}}
          env:
{{/*          {{- include "common.env" . | nindent 12 }}*/}}
                      {{- .Files.Get .Values.env_file | nindent 12}}
          {{/*              {{- toYaml .Values.common.env | indent 6 }}*/}}

{{/*          imagePullPolicy: {{ .Values.imagePullPolicy }}*/}}
          workingDir: /etc/hyperledger
          command: [./container-scripts/container-orderer.sh]
      containers:
        - name: nginx
          image: docker.io/nginx
{{/*          imagePullPolicy: {{ .Values.imagePullPolicy }}*/}}

